import os
import re
from dataclasses import dataclass
from typing import List, Optional, Tuple

import streamlit as st
from dotenv import load_dotenv

from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import (
    TranscriptsDisabled,
    NoTranscriptFound,
    VideoUnavailable,
)

from openai import OpenAI

# ----------------------------
# Config / Setup
# ----------------------------
load_dotenv()

st.set_page_config(page_title="YouTube Summarizer", page_icon="🧠", layout="wide")

DEFAULT_MODEL = os.getenv("OPENAI_MODEL", "gpt-4.1-mini")  # robust + günstig
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None

YOUTUBE_REGEX = re.compile(
    r"(?:https?://)?(?:www\.)?"
    r"(?:youtube\.com/(?:watch\?v=|shorts/|embed/)|youtu\.be/)"
    r"([A-Za-z0-9_-]{11})"
)

# ----------------------------
# Helpers
# ----------------------------
@dataclass
class SummarizeOptions:
    style: str
    length: str
    audience: str
    language: str
    focus: str
    chapters: bool
    quotes: bool
    action_items: bool


def extract_video_id(url: str) -> Optional[str]:
    if not url:
        return None
    m = YOUTUBE_REGEX.search(url.strip())
    return m.group(1) if m else None


@st.cache_data(show_spinner=False)
def fetch_transcript(video_id: str, preferred_langs: Tuple[str, ...]) -> str:
    """
    Fetches transcript text if available.
    Tries preferred languages in order.
    """
    transcripts = YouTubeTranscriptApi.list_transcripts(video_id)

    # Try manual transcripts first, then autogenerated, per language preference
    for lang in preferred_langs:
        try:
            t = transcripts.find_manually_created_transcript([lang])
            parts = t.fetch()
            return "\n".join(p["text"] for p in parts)
        except Exception:
            pass

        try:
            t = transcripts.find_generated_transcript([lang])
            parts = t.fetch()
            return "\n".join(p["text"] for p in parts)
        except Exception:
            pass

    # If nothing worked, raise for outer handling
    raise NoTranscriptFound(video_id)


def clean_transcript(text: str) -> str:
    # Remove artifacts like [Music], excessive whitespace, etc.
    text = re.sub(r"\[.*?\]", "", text)
    text = re.sub(r"\s+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def chunk_text_by_words(text: str, max_words: int = 1800) -> List[str]:
    words = text.split()
    if len(words) <= max_words:
        return [text]
    chunks = []
    start = 0
    while start < len(words):
        end = min(start + max_words, len(words))
        chunk = " ".join(words[start:end])
        chunks.append(chunk)
        start = end
    return chunks


def build_system_prompt(opts: SummarizeOptions) -> str:
    return (
        "Du bist ein sehr präziser Redakteur und Analyst für Video-Inhalte. "
        "Du fasst Inhalte strukturiert zusammen, ohne zu halluzinieren. "
        "Wenn etwas im Transkript nicht eindeutig belegt ist, markiere es als Unsicherheit."
    )


def build_user_prompt(transcript: str, opts: SummarizeOptions) -> str:
    extras = []
    if opts.chapters:
        extras.append("Erstelle sinnvolle Kapitelüberschriften (mit kurzen Beschreibungen).")
    if opts.quotes:
        extras.append("Extrahiere 3–7 starke Zitate (kurz, prägnant).")
    if opts.action_items:
        extras.append("Leite konkrete Action Items / nächste Schritte ab.")

    extras_txt = "\n- " + "\n- ".join(extras) if extras else ""

    return f"""
Kontext: Du bekommst das Transkript eines YouTube-Videos.

Anforderungen:
- Stil: {opts.style}
- Länge: {opts.length}
- Zielgruppe: {opts.audience}
- Sprache der Ausgabe: {opts.language}
- Fokus: {opts.focus}

Zusätzliche Elemente:{extras_txt if extras_txt else "\n- Keine"}

Output-Format (immer in Markdown):
1) Titel (falls aus Inhalt ableitbar, sonst neutral)
2) Kurzüberblick (2–4 Sätze)
3) Hauptpunkte (je nach Länge)
4) Details / Beispiele (wenn Länge = lang oder Stil das verlangt)
5) (Optional) Kapitel
6) (Optional) Zitate
7) (Optional) Action Items

Transkript:
\"\"\"
{transcript}
\"\"\"
""".strip()


def call_llm(prompt: str, system: str, model: str = DEFAULT_MODEL, max_output_tokens: int = 900) -> str:
    if not client:
        raise RuntimeError("OPENAI_API_KEY fehlt. Bitte als ENV setzen oder in Streamlit Secrets hinterlegen.")

    resp = client.responses.create(
        model=model,
        input=[
            {"role": "system", "content": system},
            {"role": "user", "content": prompt},
        ],
        max_output_tokens=max_output_tokens,
    )
    return resp.output_text


def summarize_transcript(transcript: str, opts: SummarizeOptions) -> str:
    transcript = clean_transcript(transcript)
    chunks = chunk_text_by_words(transcript, max_words=1800)

    system = build_system_prompt(opts)

    # Output length heuristics
    length_to_tokens = {
        "kurz (5 bullets)": 450,
        "mittel": 900,
        "lang (mit Beispielen)": 1400,
    }
    max_out = length_to_tokens.get(opts.length, 900)

    if len(chunks) == 1:
        user_prompt = build_user_prompt(chunks[0], opts)
        return call_llm(user_prompt, system, max_output_tokens=max_out)

    # Map: summarize each chunk
    partials = []
    for i, ch in enumerate(chunks, start=1):
        chunk_prompt = build_user_prompt(ch, opts) + f"\n\nHinweis: Das ist Teil {i}/{len(chunks)}. Erzeuge eine Teilzusammenfassung."
        partials.append(call_llm(chunk_prompt, system, max_output_tokens=650))

    # Reduce: summarize summaries
    merged = "\n\n---\n\n".join(partials)
    reduce_prompt = f"""
Du bekommst mehrere Teilzusammenfassungen eines langen Videos.
Erzeuge daraus eine konsistente, nicht redundante Gesamtsummary nach diesen Einstellungen:
- Stil: {opts.style}
- Länge: {opts.length}
- Zielgruppe: {opts.audience}
- Sprache: {opts.language}
- Fokus: {opts.focus}

Teilzusammenfassungen:
\"\"\"
{merged}
\"\"\"
""".strip()

    return call_llm(reduce_prompt, system, max_output_tokens=max_out)


# ----------------------------
# UI
# ----------------------------
st.title("🧠 YouTube / Video Summarizer (Streamlit + OpenAI)")
st.caption("YouTube-Link rein → Transkript → Zusammenfassung nach deinen Vorgaben.")

with st.sidebar:
    st.subheader("Einstellungen")

    style = st.selectbox(
        "Stil",
        ["Executive Summary", "Bullet Points", "Lernnotizen", "Tweet-Thread", "Blogpost", "Meeting Minutes"],
        index=0,
    )
    length = st.selectbox("Länge", ["kurz (5 bullets)", "mittel", "lang (mit Beispielen)"], index=1)
    audience = st.selectbox("Zielgruppe", ["Anfänger", "Fortgeschritten", "Experte"], index=1)
    language = st.selectbox("Ausgabe-Sprache", ["Deutsch", "Englisch", "Originalsprache"], index=0)
    focus = st.selectbox(
        "Fokus",
        ["Key Takeaways", "Schritt-für-Schritt", "Argumente/Thesen", "Zahlen & Fakten", "Kontroverse"],
        index=0,
    )

    chapters = st.checkbox("Kapitel erzeugen", value=True)
    quotes = st.checkbox("Zitat-Highlights", value=False)
    action_items = st.checkbox("Action Items", value=True)

    st.divider()
    model = st.text_input("Model (optional)", value=DEFAULT_MODEL, help="z.B. gpt-4.1-mini")

col1, col2 = st.columns([2, 1], gap="large")

with col1:
    youtube_url = st.text_input("YouTube Link", placeholder="https://www.youtube.com/watch?v=...")
    st.write("Oder: Transkript manuell einfügen (Fallback, falls YouTube keins liefert):")
    manual_transcript = st.text_area("Transkript (optional)", height=160, placeholder="Hier Transkript einfügen...")

with col2:
    st.subheader("API-Key")
    api_key_input = st.text_input(
        "OpenAI API Key (nur falls nicht via ENV/Secrets gesetzt)",
        type="password",
        value="",
        help="Empfohlen: OPENAI_API_KEY über Streamlit Secrets setzen.",
    )
    if api_key_input:
        os.environ["OPENAI_API_KEY"] = api_key_input
        client = OpenAI(api_key=api_key_input)

    st.divider()
    st.subheader("Hinweis")
    st.write("- Manche Videos haben keine Captions.\n- Dann nutze den Transkript-Fallback.\n- Lange Videos werden automatisch gechunkt.")

opts = SummarizeOptions(
    style=style,
    length=length,
    audience=audience,
    language=language,
    focus=focus,
    chapters=chapters,
    quotes=quotes,
    action_items=action_items,
)

run = st.button("Zusammenfassen", type="primary", use_container_width=True)

if run:
    vid = extract_video_id(youtube_url)
    transcript_text = ""

    with st.spinner("Transkript laden…"):
        if manual_transcript.strip():
            transcript_text = manual_transcript.strip()
        else:
            if not vid:
                st.error("Bitte einen gültigen YouTube-Link eingeben (oder Transkript manuell einfügen).")
                st.stop()

            # Language preference based on UI
            if language == "Deutsch":
                pref = ("de", "en")
            elif language == "Englisch":
                pref = ("en", "de")
            else:
                pref = ("de", "en")

            try:
                transcript_text = fetch_transcript(vid, pref)
            except (TranscriptsDisabled, NoTranscriptFound):
                st.warning("Kein Transkript gefunden oder Captions deaktiviert. Bitte Transkript manuell einfügen.")
                st.stop()
            except VideoUnavailable:
                st.error("Video nicht verfügbar (privat, gelöscht oder regional blockiert).")
                st.stop()
            except Exception as e:
                st.error(f"Fehler beim Transkript-Laden: {e}")
                st.stop()

    with st.spinner("LLM erstellt die Zusammenfassung…"):
        try:
            summary = summarize_transcript(transcript_text, opts)
        except Exception as e:
            st.error(f"Fehler beim Zusammenfassen: {e}")
            st.stop()

    st.success("Fertig ✅")

    st.subheader("Zusammenfassung")
    st.markdown(summary)

    st.download_button(
        "Download als Markdown",
        data=summary.encode("utf-8"),
        file_name="summary.md",
        mime="text/markdown",
        use_container_width=True,
    )